# Generated by Django 2.2 on 2019-12-14 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('support_processor', models.TextField()),
                ('slots_memory', models.IntegerField(max_length=1)),
                ('support_memory', models.IntegerField()),
                ('integrated_video', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GraphicCard')),
                ('memory', models.ManyToManyField(to='core.Memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Processor')),
            ],
        ),
    ]
