# Generated by Django 2.2 on 2019-12-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildpc',
            options={'ordering': ('client',)},
        ),
        migrations.AddField(
            model_name='buildpc',
            name='client',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='product',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='buildpc',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motherboard'),
        ),
        migrations.AlterField(
            model_name='buildpc',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Processor'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='slots_memory',
            field=models.IntegerField(),
        ),
    ]
